/* eslint-disable @typescript-eslint/naming-convention */

export interface Manifest {
    Author?: string,
    Name: string,
    Punchline?: string,
    Description?: string,
    Changelog?: string,
    Tags?: string[],
    CategoryTags?: string[],
    IsHide: boolean,
    InternalName: string,
    AssemblyVersion: string,
    TestingAssemblyVersion?: string,
    IsTestingExclusive: boolean,
    RepoUrl?: string,
    ApplicableVersion?: string,
    DalamudApiLevel?: number,
    DownloadCount: number,
    LastUpdate: number,
    DownloadLinkInstall?: string,
    DownloadLinkUpdate?: string,
    DownloadLinkTesting?: string,
    LoadRequiredState: number,
    LoadSync: boolean,
    LoadPriority: number,
    CanUnloadAsync: boolean,
    ImageUrls?: string[],
    IconUrl?: string,
    AcceptsFeedback?: boolean,
    FeedbackMessage?: string,
    _isDip17Plugin?: boolean,
    _Dip17Channel?: string,
}
