name: Regenerate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: corepack enable

      - run: pnpm install

      - run: pnpm lint

      - run: pnpm build

      - run: pnpm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate PluginMaster
          add: 'pluginmaster.json pluginmaster_gh.json store/*/pluginmaster.json store/*/*.zip'
